class Errors:

    ALREADY_CREATED = 'ALREADY_CREATED'
    PUBLISH_ERROR = 'PUBLISH_ERROR'
    NO_BALANCERS = 'NO_BALANCERS'
    NO_BOT = 'NO_BOT'
    NO_COMMAND = 'NO_COMMAND'
    NO_WORKERS = 'NO_WORKERS'
