apiVersion: v1
kind: Pod
metadata:
  name: postgres
  labels:
    postgres: postgres
spec:
  volumes:
  - name: postgres
    hostPath:
      path: /data/postgres
      type: DirectoryOrCreate
  containers:
  - name: postgres
    image: postgres:16-alpine3.19
    volumeMounts:
    - mountPath: /var/lib/postgresql/data
      name: postgres
    ports:
    - name: postgres
      containerPort: 5432
      protocol: TCP
    env:
    - name: POSTGRES_USER
      value: postgres
    - name: POSTGRES_PASSWORD
      value: postgres
    - name: POSTGRES_DB
      value: postgres
---
apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  selector:
    postgres: postgres
  clusterIP: None
  ports:
  - name: postgres
    protocol: TCP
    port: 5432
    targetPort: postgres
---
apiVersion: v1
kind: Pod
metadata:
  name: rabbitmq
  labels:
    rabbitmq: rabbitmq
spec:
  containers:
  - name: rabbitmq
    image: rabbitmq:3.12-management-alpine
    ports:
    - name: rabbitmq
      containerPort: 5672
      protocol: TCP
    - name: rabbitmq-mg
      containerPort: 15672
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
spec:
  selector:
    rabbitmq: rabbitmq
  clusterIP: None
  ports:
  - name: rabbitmq
    protocol: TCP
    port: 5672
    targetPort: rabbitmq
  - name: rabbitmq-mg
    protocol: TCP
    port: 15672
    targetPort: rabbitmq-mg
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    redis: redis
spec:
  containers:
  - name: redis
    image: redis/redis-stack-server:7.2.0-v8
    ports:
    - name: redis
      containerPort: 6379
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: redis
spec:
  selector:
    redis: redis
  clusterIP: None
  ports:
  - name: redis
    protocol: TCP
    port: 6379
    targetPort: redis
