version: "3"

services:
  api:
    image: api:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
      SECRET: secret
    networks:
      - appnet
    deploy:
      restart_policy:
        condition: none
    init: true
    command: ["uvicorn", "api_server:app", "--root-path", "/api/v1", "--proxy-headers",
              "--forwarded-allow-ips", "'*'", "--host", "0.0.0.0", "--port", "8080"]

  balancer:
    image: balancer:latest
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      RABBITMQ_HOST: rabbitmq
      REDIS_HOST: redis
    networks:
      - appnet
    deploy:
      restart_policy:
        condition: none
    init: true
    command: ["python", "balancer.py", "--workers", "1", "--instances", "2"]

networks:
  appnet:
