version: "3"

services:
  postgres:
    image: postgres:16-alpine3.19
    user: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - appnet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 1

  redis:
    image: redis/redis-stack-server:7.2.0-v8
    ports:
      - 6379:6379
    networks:
      - appnet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 1

  rabbitmq:
    image: rabbitmq:3.12-management-alpine
    user: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    networks:
      - appnet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 1

  caddy:
    image: caddy:2.7-alpine
    ports:
      - 80:80
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - monitor
      - appnet
    deploy:
      mode: global
      restart_policy:
        condition: on-failure
        max_attempts: 1

volumes:
  postgres_data:
  caddy_data:
  caddy_config:

networks:
  appnet:
  monitor:
