apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  template:
    metadata:
      labels:
        {{- toYaml .Values.labels | nindent 8 }}
        {{- if .Values.dev }}
          {{- toYaml .Values.dev.labels | nindent 8 }}
        {{- end }}
    spec:
      containers:
      - name: {{ .Values.name }}
        image: {{ .Values.image.name }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        command: {{ .Values.command }}
        args: {{ toYaml .Values.args | nindent 10 }}
        livenessProbe:
          {{- toYaml .Values.livenessProbe | nindent 10 }}
        readinessProbe:
          {{- toYaml .Values.readinessProbe | nindent 10 }}
        ports:
          {{- toYaml .Values.deployment.ports | nindent 10 }}
        env:
          {{- toYaml .Values.env | nindent 10 }}
        envFrom:
          {{- toYaml .Values.envFrom | nindent 10 }}
        resources:
          {{- toYaml .Values.resources | nindent 10 }}
