apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}
  labels:
    {{- toYaml .Values.labels | nindent 4 }}
spec:
  selector:
    app: {{ .Values.name }}
  ports:
    {{- toYaml .Values.service.ports | nindent 6 }}
