{{- if .Values.canary }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.canary.name }}
  labels:
    {{- toYaml .Values.canary.labels | nindent 4 }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.canary.name }}
  minReplicas: {{ default .Values.autoscaling.minReplicas .Values.canary.autoscaling.minReplicas }}
  maxReplicas: {{ default .Values.autoscaling.maxReplicas .Values.canary.autoscaling.maxReplicas }}
  metrics:
    {{- if or .Values.canary.autoscaling.targetCPUUtilizationPercentage .Values.autoscaling.targetCPUUtilizationPercentage }}
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: {{ or .Values.canary.autoscaling.targetCPUUtilizationPercentage .Values.autoscaling.targetCPUUtilizationPercentage }}
    {{- end }}
    {{- if or .Values.canary.autoscaling.targetMemoryUtilizationPercentage .Values.autoscaling.targetMemoryUtilizationPercentage }}
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: {{ or .Values.canary.autoscaling.targetMemoryUtilizationPercentage .Values.autoscaling.targetMemoryUtilizationPercentage }}
    {{- end }}
{{- end }}